### ISSUE TITLE
Theater of Pain has no date

### ISSUE THREAD

**Issue by Accuracyx** [Tomslack/ManbabyDungeonTools#33]
I imported the MDTImport
but Theater of Pain has no date...

**Comment by Maczuga** [comment]
![image](https://user-images.githubusercontent.com/544349/103204679-2c76bb00-48f8-11eb-83c9-4fbb61d03f46.png)
Can't confirm that.

**Comment by srenauld** [comment]
@Maczuga he imported the data into old MDT. I'm... honestly not sure, never actually did that (since we have newer data than MDT at this point), and would need to test to figure out what went wrong.

anyway, @Alarzzf, recommendation for now would be to just install this add-on rather than trying to import the data, if it really struggles. download a zip for 1.1.2 in releases and unzip in your add-on folder, or let wowup manage it for you.

I'll test what went wrong later, see if I can replicate.

**Comment by Accuracyx** [comment]
I mean this
![QQ图片20201228181444](https://user-images.githubusercontent.com/43119930/103207151-91520580-4938-11eb-8155-0da794c7c199.png)
only Theater of Pain has no date of spell
![QQ图片20201228181642](https://user-images.githubusercontent.com/43119930/103207263-d8d89180-4938-11eb-8072-f55b16f7fc2f.png)
the other dungeon is fine

**Comment by Accuracyx** [comment]
my bad data...
not date

**Comment by srenauld** [comment]
Those mobs never had abilities in MDT!

I'll keep your issue open. I'm working on a tool to automate data capture like this (ability usage particularly); when that's done we'll have ways to add those in automatically.

For now, though, I'll go over my own key logs and map out abilities for them.

**Comment by Accuracyx** [comment]
@srenauld i appreciate that.

**Comment by srenauld** [comment]
Version `1.1.6` (available on the latest releases and through wowup) should contain as much of the spell data as I could find from my own logs for ToP.

I've also made some improvements to show spell details (such as Xav's combo), with the intention to expand on this further later on to properly guide people!
