### ISSUE TITLE
Version number in ManbabyDungeonTools.toc

### ISSUE THREAD

**Issue by ueberBrot** [Tomslack/ManbabyDungeonTools#34]
Don't know if you want to adjust the version in the [ManbabyDungeonTools.toc](https://github.com/Tomslack/ManbabyDungeonTools/blob/7f8407956914ed1daabec8e450b07aeb89d7b0b8/ManbabyDungeonTools.toc#L4). It still says `3.3.4`. Should be changed to ManbabyDungeonTools newest release.
To automate this perhaps a tool like [`bump2version`](https://github.com/c4urself/bump2version) can be used for this purpose.

Also, you might want to edit the author and list Nnoggie as the original author but not as the author of this tool? I mean this is only a small thing and not necessary but it separates more form the "original" one. 
And looking in the future when you want to add new functionality or as stated by @srenauld "untangle it" it would be beneficial I think. 

But its just a thought :).

**Comment by srenauld** [comment]
Hey @ueberBrot !

The version in the toc on the repository is a placeholder there purely for development purposes. As you can see on the github actions [here](https://github.com/Tomslack/ManbabyDungeonTools/blob/main/.github/workflows/tagged-release.yml#L43), whenever one of us tags a release with a version (for instance, [v1.1.2](https://github.com/Tomslack/ManbabyDungeonTools/releases/tag/v1.1.2) done at like 3am today), github takes charge of the packaging, re-versioning and everything else!

As a result, if you're cloning the repo rather than getting something from the releases, the version will be a placeholder used purely for development to get WoW addon devs to be able to load the addon even when working on their own branch. The releases themselves are properly versionned, tagged and everything.

I'm trying to get Guilty to agree to a rebranding of this so it can be less of a temper tantrum and more of a continuing work. When that's agreed and we have a real name (for instance), the readme will likely change a lot.

Thank you for the issue, though - it's great to hear that people have eyes on this :-)

**Comment by ueberBrot** [comment]
> The version in the toc on the repository is a placeholder there purely for development purposes. 

Yeah I checked the download and it was the right version number. I probably should have put that better :smirk:. I didn't see that you added a workflow (nice one btw. :thumbsup:). 

> Thank you for the issue, though - it's great to hear that people have eyes on this :-)

I will do so in the future as well (if there are any lol) and provide a PR if I can fix them.

Keep up the good work.
