### ISSUE TITLE
Hide/Show Minimap button doesn't work

### ISSUE THREAD

**Issue by fludotlove** [Tomslack/ManbabyDungeonTools#36]
In "Interface > Addons > ManbabyDungeonTools" there's an option to toggle the minimap icon, but no matter what it's always showing the minimap icon.

**Comment by srenauld** [comment]
Hey @fludotlove !

I tried this on 1.1.6 after I was done with the ToP data edits and could not reproduce. Can you check if it still happens on that version?

**Comment by fludotlove** [comment]
It's working now if I do a /reload with 1.1.6 - I was using 1.1.2 previously so seems like something during those patch versions fixed it. Closing issue, thanks for resolving.

**Comment by srenauld** [comment]
Perfect!

It was probably due to the name changes - whether to display the minimap icon is a global variable defined [here](https://github.com/LetsTimeIt/DungeonTools/blob/main/DungeonTools.lua#L146), so it is perfectly possible that one of the many search-and-replaces that happened over the past 2 days nuked that feature (and the route saving from issue #35 ) in the process.
