### ISSUE TITLE
Add-on not working at all

### ISSUE THREAD

**Issue by Lurtzthetank** [Tomslack/ManbabyDungeonTools#6]
First off, thanks guys for doing this! 
Secondly, I am having an issue with the add-on loading at all. I am get 12 Lua Warnings. 
error loading: Libstub
Aceaddon-3.0
Callbackhandler-1.0
AceDB-3.0
AceGUI-3.0
ChatThrottleLib
AceComm-3.0
AceSerializer-3.0
LibCompress
LibDataBroker-1.1
LibDBIcon-1.0
AceConfig-3.0

**Comment by ShmooDude** [comment]
It's because the libraries are missing.  I believe they're normally included when a build is uploaded to curseforge but not typically included in the GitHub repository.

If you want to fix it yourself, you can download a copy of MythicDungeonTools and copy the `libs` folder into ManbabyDungeonTools and I would bet that would work (I had to do the same thing when I downloaded 3.3.4 of MythicDungeonTools from GitHub).

**Comment by Tomslack** [comment]
Should be fixed now.

**Comment by Lurtzthetank** [comment]
not working still.

edit: add-on is working after copying the libs folder from mythicdungeontools. 
Now the logo on the mini-map has disappeared. Not trying to be a pain in the ass. Just trying to help! 
Thanks again.
