### ISSUE TITLE
He changed his mind

### ISSUE THREAD

**Issue by LordDeimos666** [Tomslack/ManbabyDungeonTools#66]
https://t.co/Pt7Hzw0xQK

**Comment by MrJeffer** [comment]
Maybe the devs that work on this addon could work with Nnoggie?

**Comment by srenauld** [comment]
I've reached out to him privately (before this snafu, we actually got on decently. he's been instrumental in getting captions going for the RWF on echo's side).

I do think there is value in continuing with this. In many ways, there is value in having more than one alternative, and it also means being able to pivot in different paths while also maintaining a common core.

Deduplication of work mapping mobs makes no sense, for instance. It's effort that could be spent developing kickass features. Somebody has to do it, but that doesn't mean every add-on should.

I'm personally in favor of keeping this and extending it; even before this, there were things that irked me with MDT - for all its features for advanced users and high key pushers, it lacked some of the hints, tips and features that would be useful to groups starting with m+, in more ways than one. This could be an area to explore.

I'm completely open to suggestions, though - don't hesitate to speak up on here or via DMs on discord (Mandl#0001). Now is the time to all sit down and discuss the future 😄

**Comment by FilthySerf** [comment]
I agree with Srenauld. It's good to keep this version going as well. It's good to have alternative addon choices for everything. DBM and BigWigs are a good example, they both achieve the same goal, but have their own set of features.

**Comment by LordDeimos666** [comment]
I agree also with @srenauld, was pointing out his decision, and also agree with some feature that the addon was lacking that this fork has polished imo.

Let's see how he's doing right now imho.

**Comment by MateusRoscoe** [comment]
I would add that we also can't know if nnoggie will keep this instance or not in the future and there is good value in having an alternative so the community isn't dependent on just his version.

**Comment by kingreboot** [comment]
for this addon, will you still make it so importing data between this one and Mythic dungeon tool will work together or will this mean a split and no longer be associated with the other addon

**Comment by srenauld** [comment]
@kingreboot the data is already slightly incompatible (but not to a point where importing `dungeonEnemies` from this to MDT would cause it to break). We extended and added a ton of things including combo spells over the past 3 days.

FWIW, in an absolutely ideal situation, I'd try to get the following:
- Standardize route serialization (so addons can talk to each other), with mob data bundled in (so a route no longer gets fucked if you update MDT and some mobs were removed/added/changed)
- Standardize and split the mob DB from either addon (So there's no duplication of work)

That way both sides get to build features rather than reinventing the wheel or racing to reinvent the wheel.

Obviously, I'm waiting to hear on whether that's a good idea or not, and it's one of the many fronts that can be worked on.

**Comment by DomGrieco** [comment]
@srenauld I think if this project decides to continue it will be critical that MDT and DT are compatible and one can import the same paths between the two.

**Comment by srenauld** [comment]
@DomGrieco Takes two to tango on that front. Personally, I'm all for it. It'd fucking suck to have to tell people like the folks at raider.io "Hey, look, we use _this format_".

There have been similar things in the long history of software development, things about competing, proprietary formats, and they've never ended well. The best example is how Microsoft essentially [promised never to enforce patents on any of their formats, and worked to openly spec things out so everybody gains access to office features irrespective of OS](https://en.wikipedia.org/wiki/Microsoft_Open_Specification_Promise) and it has been a huge boon for all parties involved, for example.

So, yeah, it's one of the areas to watch, and I'll make sure you're all in the loop.

I've also been in the process of setting up a discord server for this, seeing as sorting feedback and things through github is kind of straining after a while. I was waiting for the logo designer to finalize the logo (yes, there's a logo on the way), but as it stands, especially in light of this, I don't think there's a reason to wait.

**Comment by travisneids** [comment]
Just adding my two cents that I agree with @srenauld and most voices being echoed here. I for one will plan to continue to contribute to this project. It's never a bad idea to get a new perspective on old things.

**Comment by madar2252** [comment]
I am happy with this project, there are so many fresh idea, and so many fixes within a few days. Maybe to create a library with mob data, what both addons are using is a good idea, but I understand it's not up only to you. I am not sharing routes often with others, so I would keep using this one, even if not compatible.

**Comment by itsmeAnRa** [comment]
I would simply prefer using an addon run by the community rather than a single person which is involved in the competitive scene.
I see many many features that could see the light in no time thanks to contributors awesome work. It will also reduce the stress given to Nnoggie from the needs for this crucial addon.
